<?php
		$visibility= array(Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
							Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG);
		$storeId    = Mage::app()->getStore()->getId();
		$_featcategory = Mage::getModel('catalog/category')->load(68);
		//replace 68 with the id of your featured category
		$_productCollection = Mage::getResourceModel('catalog/product_collection')->addAttributeToSelect('*')
    			->addAttributeToFilter('visibility', $visibility)->addAttributeToFilter('status',1)
		        ->setStoreId($storeId)->addStoreFilter($storeId)
                ->joinField(
                        'qty',
                        'cataloginventory/stock_item',
                        'qty',
                        'product_id=entity_id',
                        '{{table}}.stock_id=1',
                         'left'
                )->addAttributeToFilter('qty', array('gt' => 0))                 
    		    ->addCategoryFilter($_featcategory); //feature category to list first
			//->setPageSize(50);	// number of products to list per page view
		//$this->getChild('toolbar')->setCollection($_productCollection);
		//print_r($this->debug());
		//echo get_class($this);
		$toolbar = Mage::getBlockSingleton('catalog/product_list')->getToolbarBlock();
		$toolbar->setCollection($_productCollection);
		echo $toolbar->getToolbarHtml();
		//echo getPagerHtml();
?>
<?php
	//$_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
	<div class="category-products">
		<?php echo $this->getToolbarHtml(); ?>
		<?php // List mode ?>
		<?php if($this->getMode()!='grid'): ?>
		<?php $_iterator = 0; ?>
		<ol class="products-list" id="products-list">
			<?php foreach ($_productCollection as $_product): ?>
			<?php	$stocklevel = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();?>
			<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
			<?php // Product Image ?>
			<?php $wineCategory=$_product->getResource()->getAttribute('product_type')->getFrontend()->getValue($_product); ?>
			<?php if($wineCategory=='White'): ?>
				<?php $color='#699542'; ?>
			<?php elseif($wineCategory=='Rose'): ?>
				<?php $color='#FF0099'; ?>
			<?php elseif($wineCategory=='Champagne'): ?>
				<?php $color='#dd9a32'; ?>
			<?php else: ?>
				<?php $color='#cc0000'; ?>
			<?php endif; ?>
			<?php //$color=$_product->getResource()->getAttribute('product_type')->getFrontend()->getValue($_product)=='White' ? '#699542' : '#cc0000';?>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
					<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
				<?php // Product description ?>
            <div class="product-shop check-product-shop" style="">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name check-product-name" style="">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>" style="color:<?php echo $color; ?>">
							<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
						</a>
					</h2>
                    <div class="list_bottle_size" style=""><strong><?php echo $_product->getResource()->getAttribute('bottle_size')->getFrontend()->getValue($_product);?></strong></div>
                    <div class="list_wine_type" style=""><strong><?php echo $_product->getResource()->getAttribute('product_type')->getFrontend()->getValue($_product);?> </strong></div>
                    <!--<p><?php //echo 'Stock :'.number_format($_product->getQty());?></p>-->
					<?php if($_product->getQty()<13):?>
						<p><?php echo 'Stock :'.number_format($_product->getQty());?></p>
					<?php else: ?>
						<p><?php echo $storeId==4 ? '在庫あり':'In Stock' ?></p>
					<?php endif; ?>
                    <?php // review of a product at any page
						$_reviews = Mage::getModel('review/review')->getResourceCollection();
						$_reviews->addStoreFilter( Mage::app()->getStore()->getId())->addEntityFilter('product', $_product->getId())
									->addStatusFilter( Mage_Review_Model_Review::STATUS_APPROVED )
									->setDateOrder()
									->addRateVotes();
						$avg = 0;
						$ratings = array();
						if (count($_reviews) > 0):
							foreach ($_reviews->getItems() as $_review): ?>
								<?php foreach( $_review->getRatingVotes() as $_vote ): ?>
									<?php $ratings[] = $_vote->getValue(); ?>
								<?php endforeach; ?>
							<?php endforeach;
							$avg = array_sum($ratings)/count($ratings); 
						endif;
						$review_url = Mage::getUrl('review/product/list', array('id'=>$_product->getId(), 'category'=> $_product->getCategoryId()));
                    ?>
                    <?php if($avg > 0) { ?>
                    <div class='ratings'>
                    <div class='rating-box'>
                    <div class='rating' style='width: <?php echo ceil($avg) ; ?>%;'></div>
                    </div>
                    <div class="rating_point_value"><?php echo number_format($avg/20,1)?></div>
                        <p class="rating-links">
                            <a href="<?php echo $review_url;?>"><?php echo count($ratings);?><?php echo $storeId==4 ? 'レビュー（S）':'Review(s)' ?></a>
                        <span class="separator">|</span>
                        <a href="<?php echo $review_url;?>#review-form"><?php echo $storeId==4?'あなたのレビューを追加':'Add Your Review'?></a>
                        </p>
                    </div>

                    <?php } else { ?>
                    <div class='ratings'>
                    <div class='rating-box'>
                    <div class='rating' style='width: <?php echo ceil($avg) ; ?>%;'></div>
                    </div>
                        <p class="rating-links">
                        <a href="<?php echo $review_url;?>#review-form"><?php echo $storeId==4 ? '口コミを投稿してください。':'Write Review' ?></a>
                        </p>
                    </div>

                    <?php } ?>
                    <div><?php //echo $this->getReviewsSummaryHtml($_product, false, false)?></div>

                    <div class="desc std review-srt-desc" style="">
                       <?php    $sdesc = nl2br($_product->getShortDescription());
                                $sdesc = trim($sdesc);
                                $limit = 165;
                                if (strlen($sdesc) > $limit):
									$sdesc = substr($sdesc, 0, strrpos(substr($sdesc, 0, $limit), ' '));
                                endif; ?>
                       <p><?php echo $sdesc."..."; ?></p>

                        <?php //echo $_helper->productAttribute($_product,  nl2br($_product->getShortDescription()), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $_productNameStripped; ?>" class="link-learn readmore-review-link" style="color:<?php echo $color; ?>"><?php echo $storeId==4 ? '続きを読む' : 'Read More'; ?></a>
                    </div>
                   <!-- <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>-->
                </div>
            </div>
             <?php
			  if($_product->getSpecialPrice()){
			  $discount=($_product->getPrice() - $_product->getSpecialPrice());

			  $discount= ( $discount/$_product->getPrice())*100;

			  $grapeoff_price=$_product->getSpecialPrice();
			  }
			  else{
			  $discount=0;
			  $grapeoff_price=$_product->getPrice();
			  }
			  ?>
            <div class="price-info" style="text-align: left !important;">
                <div class="price-box">

                    <p class="old-price">
                    <span class="price-label"><?php echo $storeId==4 ? '希望小売価格':'Suggested Retail Price'; ?>&nbsp;</span>
                    <span id="old-price" class="price"><?php echo $formattedPrice = Mage::helper('core')->currency($_product->getPrice(),true,false); ?></span>
                    </p>

                    <p class="discount-percent">
                    <span class="price-label"><?php echo $storeId==4 ? '割引':'Discount';?></span>
                    <span id="product-price" class="price"><?php echo round($discount).'%'; ?></span>
                    </p>
                    <p class="special-price">
                    <span class="price-label"><?php echo $storeId==4? 'Grape Off 価格':'Grape Off Price'; ?>&nbsp;</span>
                    <span id="product-price" class="price"><?php echo Mage::helper('core')->currency(round($grapeoff_price),true,false); ?></span>
                    </p>
					<p>
						<span class="price-label">(<?php echo $storeId==4? '税込':'tax included'; ?>
						<?php $ffprice=($grapeoff_price*.08)+$grapeoff_price; ?>
						<?php echo Mage::helper('core')->currency(round($ffprice),true,false); ?>)
						</span>						
					</p>

        </div> <?php $buttonTitle = $this->__('Add to Cart'); ?>
                <?php //echo $this->getPriceHtml($_product, true);?>
                   <?php if($_product->isSaleable()): ?>
                            <!--<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>-->
                            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                            <p class="review-addcart-btn" style="">
                             <?php if(!$_product->isGrouped()): ?>
                             <!--<label for="qty"><?php echo $this->__('Qty') ?>:</label>-->
                             <input type="hidden" name="qty" class="qtytextbox" style="height: 26px;margin-top: 1px;" id="qty" maxlength="12" size="5" value="<?php echo ($this->getMinimalQty($_product)?$this->getMinimalQty($_product):1) ?>" />
                             <?php endif; ?>
                             <span id='ajax_loader<?php echo $_product->getId()?>' style='visibility: hidden;float: right;' class="ajax_loader"><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>'/></span>

                             <!--<button type="button" title="<?php //echo $this->__('Add to Cart') ?>" class="button btn-cart" style="padding-left: 0 0 0 55px;" onclick="setLocationAjax('<?php //echo $this->getAddToCartUrl($_product) ?>','<?php// echo $_product->getId()?>')"><span style="background:<?php //echo $color; ?>"><span><?php //echo $this->__('Add to Cart') ?></span></span></button>-->
                             <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" style="padding-left: 0 0 0 55px;" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>','<?php echo $_product->getId()?>')">
								<?php //Zend_Debug::dump($_product); ?>
								<span style="background:<?php echo $color; ?>">
									<span>
										<?php echo $storeId==4 ? 'カートに入れる':'Add to Cart'; ?>
									</span>
								</span>
							</button>
                             
                             <!--<button style="margin-left: 5px" type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="this.form.submit()"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>-->
                            </p>
                            </form>

                            <!--<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>-->
                    <?php else: ?>
                         <p class="availability out-of-stock" style="padding-top: 20px"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
            </div>
        </li>
			<?php endforeach; ?>
		</ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php //echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <!--<ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>-->
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<script type="text/javascript">
	//jQuery.noConflict();
	/*jQuery(document).ready(function(){
		jQuery('.fancybox').fancybox(
			{
			   hideOnContentClick : true,
			   width: 382,
			   autoDimensions: true,
               type : 'iframe',
			   showTitle: false,
			   scrolling: 'no',
			   onComplete: function(){
				jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
					jQuery.fancybox.resize();
				 });

			   }
			}
		);
	});*/
	function showOptions(id){
		//jQuery('#fancybox'+id).trigger('click');
	}
	function setAjaxData(data,iframe){
		if(data.status == 'ERROR'){
			alert(data.message);
		}else{
			if(jQuery('.block-cart')){
	            jQuery('.block-cart').replaceWith(data.sidebar);
	        }
	        if(jQuery('.header .links')){
	            //jQuery('.header .links').replaceWith(data.toplink);
	        }
	        //jQuery.fancybox.close();
			//jQuery(".vipList").not(":last").remove();
		}
	}
	function setLocationAjax(url,id){
		url += 'isAjax/1';
		
		url = url.replace("checkout/cart","ajax/index");
		//jQuery('#ajax_loader'+id).show();
                jQuery('#ajax_loader'+id).css('visibility', 'visible');
		try {
			jQuery.ajax( {
				url : url,
				dataType : 'json',
				success : function(data) {
					//jQuery('#ajax_loader'+id).hide();
                                          jQuery('#ajax_loader'+id).css('visibility', 'hidden');
                                          jQuery('#topcartqty').replaceWith('<span id="topcartqty">('+data.cartqty+')</span>');

         			setAjaxData(data,false);
					
				}
			});
		} catch (e) {
		}
	}
</script>
 
<?php endif; ?>