<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Phoenix
 * @package    Phoenix_CashOnDelivery
 * @copyright  Copyright (c) 2008-2009 Andrej Sinicyn, Mik3e
 * @copyright  Copyright (c) 2010 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <div class="input-box">
            <?php if ($this->getMethod()->getCustomText()): ?>
                <?php echo $this->getMethod()->getCustomText() ?><br />
            <?php endif; ?>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $this->getMethodCode() ?>_exclude_fee"><?php echo Mage::helper('cashondelivery')->__('Exclude COD Fee') ?></label><br/>
            <input id="<?php echo $this->getMethodCode() ?>_exclude_fee" name="payment[exclude_fee]" type="checkbox" value="1" />
        </div>
    </li>
</ul>
<script type="text/javascript">
    AdminOrder.prototype=Object.extend(AdminOrder.prototype,{
        changePaymentData : function(event){
            var elem = Event.element(event);
            if(elem && elem.method){
                var data = this.getPaymentData(elem.method);
                if (data) {
                    this.loadArea(['totals','card_validation'], true, data);
                } else {
                    return;
                }
            }
        }
    });
</script>